# Generated by Django 6.0.1 on 2026-01-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_counted_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
